<a href="https://colab.research.google.com/github/Faizan-Rashid/deep-learning-pytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch;
import pandas as pd;
import numpy as np;
import matplotlib.pyplot as plt

print(torch.__version__);

2.6.0+cu124


# Introduction to Tensors

In [ ]:
# scalar
scalar = torch.tensor(3);
print(scalar, scalar.shape);

tensor(3) torch.Size([])


In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor as python int
scalar.item();

In [ ]:
# Vector
vector  = torch.tensor([1, 2]);

vector.shape
vector

tensor([1, 2])

In [ ]:
# Matrix
Matrix = torch.tensor([
    [1,2],
    [4,6.0]
]);

Matrix

tensor([[1., 2.],
        [4., 6.]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([
    [
        [1,2,4.0],
        [4,5,6],
        [0,0,0],
        [1,1,1]
    ]
]);

TENSOR

tensor([[[1., 2., 4.],
         [4., 5., 6.],
         [0., 0., 0.],
         [1., 1., 1.]]])

In [ ]:
print(TENSOR.ndim);

3


In [ ]:
TENSOR.shape

torch.Size([1, 4, 3])

In [ ]:
# practice
t = torch.tensor([
    [
        [
            [1,1,1],
            [2,2,2],
            [6,6,6],
            [6,7,8]
        ],
         [
            [3,3,4],
            [5,5,5],
            [7,7,7],
            [6,7,8]
        ],
        [
            [3,3,4],
            [5,5,5],
            [7,7,7],
            [6,7,8]
        ]
    ],
     [
        [
            [9,9,9],
            [2,-2,1],
            [6,-6,6],
            [6,7,8]
        ],
         [
            [3,3,4],
            [5,8,5],
            [7,9,7],
            [6,7,8]
        ],
         [
            [3,3,4],
            [5,5,5],
            [7,7,7],
            [6,7,8]
        ]
    ]
])


print(t.shape);
print(t.ndim);

torch.Size([2, 3, 4, 3])
4


### Random tensors

Why Random tensors?

Its because the way many neural networks work. They start with tensors full of random numbers and the adjust those random numbers to better represent the data.

`start with randdom numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# creating random tensor of size (4,6)

random_tensor = torch.rand(4,6);

random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090]])

In [ ]:
# practice for creating an image tensor

random_image_size_tensor = torch.rand(size =  (3, 224, 224));

random_image_size_tensor

tensor([[[0.5779, 0.9040, 0.5547,  ..., 0.1519, 0.7513, 0.7269],
         [0.8572, 0.1165, 0.8596,  ..., 0.3058, 0.2057, 0.5674],
         [0.2053, 0.1745, 0.7606,  ..., 0.0947, 0.7112, 0.6579],
         ...,
         [0.5233, 0.1834, 0.8414,  ..., 0.6435, 0.4813, 0.9848],
         [0.1736, 0.1452, 0.2766,  ..., 0.4210, 0.5068, 0.5500],
         [0.3963, 0.6318, 0.8367,  ..., 0.4154, 0.5576, 0.2367]],

        [[0.2668, 0.7128, 0.1088,  ..., 0.0576, 0.4765, 0.6810],
         [0.3167, 0.6236, 0.3563,  ..., 0.3107, 0.3265, 0.7110],
         [0.7131, 0.4161, 0.9968,  ..., 0.9777, 0.2450, 0.1536],
         ...,
         [0.2428, 0.4295, 0.2029,  ..., 0.3759, 0.7192, 0.2318],
         [0.6674, 0.8720, 0.4144,  ..., 0.5113, 0.8936, 0.4637],
         [0.4770, 0.8316, 0.6461,  ..., 0.0201, 0.9082, 0.9212]],

        [[0.4963, 0.7997, 0.6234,  ..., 0.6363, 0.0600, 0.2417],
         [0.0453, 0.4890, 0.6399,  ..., 0.0440, 0.6705, 0.8744],
         [0.7760, 0.9162, 0.9622,  ..., 0.2260, 0.3504, 0.

### Zeros and Ones

In [ ]:
# tensor of all zeros

zeros  = torch.zeros(4,5);

zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(4,5);

ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
torch.zeros(5,4,3,3,2,2,1,15)

tensor([[[[[[[[0., 0., 0.,  ..., 0., 0., 0.]],

             [[0., 0., 0.,  ..., 0., 0., 0.]]],


            [[[0., 0., 0.,  ..., 0., 0., 0.]],

             [[0., 0., 0.,  ..., 0., 0., 0.]]]],



           [[[[0., 0., 0.,  ..., 0., 0., 0.]],

             [[0., 0., 0.,  ..., 0., 0., 0.]]],


            [[[0., 0., 0.,  ..., 0., 0., 0.]],

             [[0., 0., 0.,  ..., 0., 0., 0.]]]],



           [[[[0., 0., 0.,  ..., 0., 0., 0.]],

             [[0., 0., 0.,  ..., 0., 0., 0.]]],


            [[[0., 0., 0.,  ..., 0., 0., 0.]],

             [[0., 0., 0.,  ..., 0., 0., 0.]]]]],




          [[[[[0., 0., 0.,  ..., 0., 0., 0.]],

             [[0., 0., 0.,  ..., 0., 0., 0.]]],


            [[[0., 0., 0.,  ..., 0., 0., 0.]],

             [[0., 0., 0.,  ..., 0., 0., 0.]]]],



           [[[[0., 0., 0.,  ..., 0., 0., 0.]],

             [[0., 0., 0.,  ..., 0., 0., 0.]]],


            [[[0., 0., 0.,  ..., 0., 0., 0.]],

             [[0., 0., 0.,  ..., 0., 0., 0.]]]],



        

### Creating Range of tensors and tensors-like

In [ ]:
# using torch.arange()
one_to_twenty = torch.arange(start=1,end=20,step=2);

one_to_twenty

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# Creating tensor like
twenty_zeroes = torch.zeros_like(input=one_to_twenty);

twenty_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of 3 big errors we run into:
  1. Tensors not right datatype
  2. Tensors not right shape
  3. Tensors not right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.,5.,6.0],
                               dtype=None, # What is datatype of tensor
                               device=None, # What device is tensor on e.g cpu or gpu
                               requires_grad=False # Whether or not to track gradients with this tensors operations
                               );

float_32_tensor

tensor([3., 5., 6.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16);

float_32_tensor * float_16_tensor

complex_128 = torch.tensor([
    [
        [
            [
                [
                    [
                        2,3,4,5,6
                    ]
                ]
            ]
        ],
        [
              [
                [
                    [
                        2,1,1,1,1
                    ]
                ]
            ]
        ]
    ],
    [
        [
              [
                [
                    [
                        0,0,0,0,0
                    ]
                ]
            ]
        ],
        [
              [
                [
                    [
                        9,9,9,9,9
                    ]
                ]
            ]
        ]
    ]
],
                           dtype=torch.complex128);

complex_128

# create a integer tensor of same shape and size as complex_128 and multiply them
int_32= torch.full_like(input=complex_128,fill_value=-3).type(torch.int32)

int_32 * complex_128


tensor([[[[[[ -6.+0.j,  -9.+0.j, -12.+0.j, -15.+0.j, -18.+0.j]]]],



         [[[[ -6.+0.j,  -3.+0.j,  -3.+0.j,  -3.+0.j,  -3.+0.j]]]]],




        [[[[[ -0.+0.j,  -0.+0.j,  -0.+0.j,  -0.+0.j,  -0.+0.j]]]],



         [[[[-27.+0.j, -27.+0.j, -27.+0.j, -27.+0.j, -27.+0.j]]]]]],
       dtype=torch.complex128)

### Getting information from tensors (tensor attributes)

1. datatype - `tensor.dtype`
2. device - `tensor.device`
3. shape - `tensor.shape`

*   List item
*   List item



In [ ]:
any_tensor = torch.rand(size=(4, 4),dtype=torch.float16);
any_tensor

tensor([[0.4976, 0.4932, 0.4473, 0.3022],
        [0.7939, 0.0142, 0.3467, 0.1113],
        [0.8193, 0.2886, 0.5596, 0.1143],
        [0.7158, 0.5405, 0.3047, 0.4243]], dtype=torch.float16)

In [ ]:
# Getting information
print(any_tensor.dtype);
print(any_tensor.shape,);
print(any_tensor.device);

torch.float16
torch.Size([4, 4])
cpu


In [ ]:
tensor = torch.tensor([
    [1,2,3],
    [1,5,1],
    [1,1,1]
]);

torch.matmul(tensor,tensor)

tensor([[ 6, 15,  8],
        [ 7, 28,  9],
        [ 3,  8,  5]])

In [ ]:
torch.matmul(torch.rand(size=(1,10)),torch.rand(size=(10,1)))

tensor([[1.8672]])

Fixing shape issuses of matrix multiplication by **transpose**

In [ ]:
tensor_A = torch.tensor([[1,2,2],
                         [4,5,2],
                         [1,1,1]
                        ]);

tensor_B = torch.tensor([[1,2,5],
                         [4,5,3],
                         [2,2,2]
                         ]);

tens  = torch.rand(size=(3,2,4))

torch.matmul(tensor_A , tensor_B.T)

print(f"""
   {tens}
   *
   {tens}

   shape {tens.shape} * {tens.shape}

   take transpose of 1
   shape is {tens.shape} * {tens.mT.shape}

   {tens}
    *
   {tens.mT} =

   *******ANSWER*******
   {torch.matmul(tens,tens.mT)}
""")
# torch.matmul(tens , tens.mT)


   tensor([[[0.5268, 0.6694, 0.3213, 0.4008],
         [0.2892, 0.9977, 0.6649, 0.5646]],

        [[0.9323, 0.4621, 0.4027, 0.1680],
         [0.1170, 0.5063, 0.6061, 0.5141]],

        [[0.1907, 0.0445, 0.5425, 0.9580],
         [0.9967, 0.6417, 0.0839, 0.0765]]])
   *
   tensor([[[0.5268, 0.6694, 0.3213, 0.4008],
         [0.2892, 0.9977, 0.6649, 0.5646]],

        [[0.9323, 0.4621, 0.4027, 0.1680],
         [0.1170, 0.5063, 0.6061, 0.5141]],

        [[0.1907, 0.0445, 0.5425, 0.9580],
         [0.9967, 0.6417, 0.0839, 0.0765]]])

   shape torch.Size([3, 2, 4]) * torch.Size([3, 2, 4])

   take transpose of 1
   shape is torch.Size([3, 2, 4]) * torch.Size([3, 4, 2])

   tensor([[[0.5268, 0.6694, 0.3213, 0.4008],
         [0.2892, 0.9977, 0.6649, 0.5646]],

        [[0.9323, 0.4621, 0.4027, 0.1680],
         [0.1170, 0.5063, 0.6061, 0.5141]],

        [[0.1907, 0.0445, 0.5425, 0.9580],
         [0.9967, 0.6417, 0.0839, 0.0765]]])
    *
   tensor([[[0.5268, 0.2892],
         [0.6694, 

Finding min, max, mean, sum. (tensor aggregation)

In [ ]:
a = torch.arange(1,101,10);

In [ ]:
a.min(), torch.min(a)

(tensor(1), tensor(1))

In [ ]:
a.max(), torch.max(a)


(tensor(91), tensor(91))

In [ ]:
# Finding mean - note: torch.mean() fuunction requires tensor to be either a floating point or complex dtype
torch.mean(a.type(torch.float32)), a.type(torch.float64).mean()

(tensor(46.), tensor(46., dtype=torch.float64))

### Finding the position min and max

In [ ]:
x = torch.arange(1,100,5);
x

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [ ]:
# finding the position of element where the minimum value is present - use argmin method
torch.argmax(x)

tensor(19)

In [ ]:
# finding the position of element where the minimum value occurs - use argmin method
torch.argmin(x)

tensor(0)

## reshaping, stacking, squeezing and unsqueezing tensors

* reshaping - reshapes tensor to some defined shape
* view - return a view of an input tensor of a certain shape but keep the same memory as the original tensor (shares the same memory as the original tensor)
* stacking - combine multiple tensors. on top of each other (vstack) or side by side (hstack)
* squeeze - removes all `1` dimensions from a target tensor
* unsqueeze - adds a `1` dimension to a target tensor
* premute - return a view of input with dimensions permuted (swapped) in a certain way.

In [ ]:
import torch

x = torch.arange(1, 10);
x.shape

torch.Size([9])

In [ ]:
# reshaping tensor - changing the shape
x_reshaped = x.reshape(1,9); # reshaped into
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# changing the view
z = x.view(1,9)
z[:,0] = 5
z,x # change in x chnages y because view of the tensor shares the same memory as original input

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
torch.stack((x,x,x,x),dim=1)

m = torch.ones(2,3);
n = torch.zeros(2,3);

torch.stack((m,n),0)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
# torch.squeeze() - removes all the single dimensions
torch.squeeze(torch.randn(2,3,1,4,1,1)).shape

torch.Size([2, 3, 4])

In [ ]:
# toch.unsqeeze - adds a single dimension to a target tensor at specific dim
torch.unsqueeze(torch.randn(2,3,1,4),2)

tensor([[[[[-0.1640, -0.7472,  0.7611,  0.6227]]],


         [[[-0.5017,  0.1270,  0.3278,  0.3091]]],


         [[[ 0.0643,  0.1142,  0.5124, -0.7454]]]],



        [[[[ 0.7567, -1.4597, -0.2478, -0.1172]]],


         [[[ 0.5644,  1.4860,  2.7381,  0.4901]]],


         [[[-0.5093,  0.4842, -0.3452, -0.3981]]]]])

In [ ]:
# rearranges the dimensions of target tensor in a specified order
x_original = torch.randn(224,224,3) # [height, width, color channel]

# permute the original tensor to chnage the order od axis (dims)
x_permuted = x_original.permute((2,0,1))
print(f"orginal shape {x_original.shape}")
print(f"permuted shape {x_permuted.shape}")

# the permuted value is a view of original tensor so they share same memory
x_permuted[:, :, 0] = 33333.00
print(f"orginal {x_original}")
print(f"permuted {x_permuted}")


orginal shape torch.Size([224, 224, 3])
permuted shape torch.Size([3, 224, 224])
orginal tensor([[[ 3.3333e+04,  3.3333e+04,  3.3333e+04],
         [-5.5248e-01,  2.1351e-01, -1.5731e+00],
         [-1.4501e-01,  1.0687e+00,  9.8133e-01],
         ...,
         [-1.6402e-01, -1.1174e+00,  3.8794e-01],
         [-1.1317e-01,  6.7211e-01,  8.8604e-01],
         [ 3.4208e-01, -3.4453e-01,  6.5074e-01]],

        [[ 3.3333e+04,  3.3333e+04,  3.3333e+04],
         [ 5.1231e-01,  1.2081e+00,  6.7790e-01],
         [-1.0469e+00, -1.5197e+00,  1.2729e-01],
         ...,
         [-9.4303e-01, -1.9632e-02, -1.3460e-01],
         [-4.8814e-01, -5.8038e-01, -5.9938e-01],
         [-8.3192e-01, -1.5856e+00,  4.3262e-02]],

        [[ 3.3333e+04,  3.3333e+04,  3.3333e+04],
         [ 8.3106e-01, -2.1112e+00, -3.3876e-01],
         [-4.3053e-01, -4.4795e-01,  1.6424e-01],
         ...,
         [ 1.2104e+00, -8.9018e-01,  4.7039e-01],
         [-2.2306e-02, -8.2207e-01, -1.2894e+00],
         [-6.16

### Indexing (selecting data from a tensor)

Indexing in Pytorch is similar to indexing in NumPy

In [ ]:
import torch
x = torch.arange(1,10).reshape(1, 3, 3)

In [ ]:
x[0][0], x[0,0], x[0,0:2,0:2] # this one is about slicing

(tensor([1, 2, 3]),
 tensor([1, 2, 3]),
 tensor([[1, 2],
         [4, 5]]))

In [ ]:
x[0][0][0] , x[0,0,0]

(tensor(1), tensor(1))

In [ ]:
# we ca use ":" to select "all" of target dimension

In [ ]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#  get all values of the 0th dimension but only 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# get index 0 of 0th & 1st dimension & all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# index on x to return 0
x[0,2,2]
# index on x to return 3, 6, 9
x[0,:,2]

tensor([3, 6, 9])

In [ ]:
torch.arange(1,5)[0:1]

tensor([1])

In [ ]:
a = torch.arange(1,21).reshape(2,5,2)
a[:,1,1]

tensor([ 4, 14])

### Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [ ]:
import torch
# import numpy as np

npArray = np.arange(1.0,9.0)
tensor = torch.from_numpy(npArray) # converting from numpy -> pytorch tensor, pytorch reflect the numpy default float64 dtpe unless specified

In [ ]:
# change the value of tensor, what this will do to tensor?
tensor[0] = 444.0
npArray, tensor

(array([444.,   2.,   3.,   4.,   5.,   6.,   7.,   8.]),
 tensor([444.,   2.,   3.,   4.,   5.,   6.,   7.,   8.], dtype=torch.float64))

In [ ]:
# tensor to numpy array
tensor = torch.ones((7))
tensor_numpy = tensor.numpy()
tensor_numpy, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

In [ ]:
tensor = tensor + 1
tensor[0] =444.0
tensor_numpy, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([444.,   2.,   2.,   2.,   2.,   2.,   2.]))

### Reproducibility (trying to take random out of random)

The way a neural network learns:
` start with random number -> tensor operations -> update random numbers to better represnt the data -> again -> again ...`

to reduce randomness in pytorch and neural networks, we use the concept of **random seed**

Essentailly what rando seed does is "flavour" the randomness

In [ ]:
random_A = torch.randn(2,3)
random_B = torch.randn(2,3)

print(random_A == random_B)

tensor([[False, False, False],
        [False, False, False]])


In [ ]:
import torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_C = torch.randn(3,2)

torch.manual_seed(RANDOM_SEED)
random_D = torch.randn(3,2)

random_C , random_D, random_C == random_D

(tensor([[ 0.3367,  0.1288],
         [ 0.2345,  0.2303],
         [-1.1229, -0.1863]]),
 tensor([[ 0.3367,  0.1288],
         [ 0.2345,  0.2303],
         [-1.1229, -0.1863]]),
 tensor([[True, True],
         [True, True],
         [True, True]]))

## Running tensors and pytorch objects on GPUs (making faster computation)

In [ ]:
import torch

# check for gpu accesss in pytorch
torch.cuda.is_available()

# which gpu
!nvidia-smi

Thu Jul  3 05:45:27 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   56C    P8             10W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
# set up device agnostic code

device  = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count the number of devices
torch.cuda.device_count()

1

### Putting tensors on GPU
the reason we want our tensors on GPU because GPUs result in faster computation


In [ ]:
tensor = torch.tensor([1,2,3])
tensor , tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# moving tensor to a gpu (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# moving tensor back to cpu
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# to fix  GPU tensor with numpy we'll move the tensor back to cpu
tensor_on_gpu.cpu().numpy()

x = torch.tensor([[1.0,2.0],[1.0,2.0]], requires_grad=True)
out = x.pow(2).sum()
out.backward()
x.grad

x.storage()

/tmp/ipython-input-166-3530226471.py:9: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x.storage()


 1.0
 2.0
 1.0
 2.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 4]